# Generated by Django 2.2.5 on 2019-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='inspirador',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
